[package]
name = "graph1"
version = "0.1.0"
edition = "2021"

#build = "build.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocl = { version = "0.19.7", optional = true }


[features]
gpu = ["ocl"]
default = ["gpu"]
#default = []



[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

#[[bench]]
#name = "graph1_benchmark"
#harness = false




[profile.release]
debug = false
#opt-level = 'z' # or 's' for size optimization with a balance between size and speed
opt-level = 's' # or 's' for size optimization with a balance between size and speed
lto=true

