use crate::core::context::gpu::GpuContext;
use crate::primitives::numeric::Numeric;
use crate::primitives::plane::{Dimensions2d, RectArea};
#[cfg(feature = "gpu")]
use ocl::{Kernel, Buffer};
use crate::buffer_op::gpu::kernel_bundle::KernelBundle;

pub fn fill_rects_bucketed<T: Numeric + Copy + 'static>(
    cpu_frame_buf: &mut [u32],
    buf_dimensions: &Dimensions2d<u32>,
    rects: &Vec<&RectArea<T>>,
    default_color: u32,
    num_buckets: Option<u32>,
    gpu_context: &mut GpuContext,
) -> Result<(), String> {
    #[cfg(feature = "gpu")]
    {
        let bundle = fill_rects_bucketed_get_kernel(
            cpu_frame_buf, buf_dimensions, rects, default_color, num_buckets, gpu_context,
        )?;
        let kernel = bundle.kernel;
        let gpu_frame_buf = bundle.buffers.get(0)
            .ok_or("No frame buffer in kernel bundle")?;

        gpu_frame_buf.write(cpu_frame_buf.as_ref()).enq()
            .map_err(|e| format!("Failed to upload frame buffer: {e}"))?;
        unsafe { kernel.enq().map_err(|e| format!("Failed to enqueue kernel: {e}"))?; }
        gpu_frame_buf.read(cpu_frame_buf).enq()
            .map_err(|e| format!("Failed to read GPU buffer: {e}"))?;
        Ok(())
    }
    #[cfg(not(feature = "gpu"))]
    {
        let _ = cpu_frame_buf;
        let _ = buf_dimensions;
        let _ = rects;
        let _ = default_color;
        let _ = num_buckets;
        let _ = gpu_context;
        Err("GPU support is not enabled at compile time.".to_string())
    }
}

/// Build and return a ready-to-enqueue OpenCL kernel for filling multiple rectangles with bucketing.
///
/// # Arguments
/// * `cpu_frame_buf` - The host buffer to fill with rectangle colors.
/// * `buf_dimensions` - Dimensions of the buffer.
/// * `rects` - Vector of rectangle areas to fill.
/// * `default_color` - Color to use for rectangles that do not have a specific color set.
/// * `n_buckets` - Optional number of buckets to use for bucketing the rectangles. If `None`, it will be autogenerated.
/// * `gpu_context` - The GPU context containing OpenCL resources.
///
pub fn fill_rects_bucketed_get_kernel<T: Numeric + Copy + 'static>(
    cpu_frame_buf: &mut [u32],
    buf_dimensions: &Dimensions2d<u32>,
    rects: &Vec<&RectArea<T>>,
    default_color: u32,
    num_buckets: Option<u32>,
    gpu_context: &mut GpuContext,
) -> Result<KernelBundle, String> {
    #[cfg(feature = "gpu")]
    {
        let num_buckets = num_buckets.unwrap_or_else(|| choose_num_buckets(rects, buf_dimensions.w, 4, 32));

        // println!("num_buckets: {num_buckets}");

        let (flat_rects, bucket_offsets, bucket_counts) =
            bucketize_rects(rects, buf_dimensions.w, num_buckets, default_color);

        let kernel_src = include_str!("fill_rects_bucketed.c");
        let kernel_name = "fill_rects_buckets";
        let program_name = "fill_rects_buckets_program";
        let buf_len = cpu_frame_buf.len();

        if gpu_context.get_program(program_name).is_none() {
            gpu_context
                .load_program(&kernel_src, program_name)
                .map_err(|e| format!("Failed to build OpenCL program: {e}"))?;
        }
        let program = gpu_context.get_program(program_name)
            .ok_or("Program not loaded (unknown error)")?;
        let queue = gpu_context.queue.as_ref().ok_or("No OpenCL queue in context")?.clone();
        let queue_ref = queue.as_ref();

        let flat_rects_buf = Buffer::<u32>::builder()
            .queue(queue_ref.clone())
            .len(flat_rects.len())
            .copy_host_slice(&flat_rects)
            .build().map_err(|e| format!("Failed to create OpenCL flat_rects buffer: {e}"))?;

        let offsets_buf = Buffer::<u32>::builder()
            .queue(queue_ref.clone())
            .len(bucket_offsets.len())
            .copy_host_slice(&bucket_offsets)
            .build().map_err(|e| format!("Failed to create OpenCL bucket_offsets buffer: {e}"))?;

        let counts_buf = Buffer::<u32>::builder()
            .queue(queue_ref.clone())
            .len(bucket_counts.len())
            .copy_host_slice(&bucket_counts)
            .build().map_err(|e| format!("Failed to create OpenCL bucket_counts buffer: {e}"))?;

        let gpu_frame_buf = gpu_context.get_or_create_buffer(buf_len, queue_ref, cpu_frame_buf)?;

        let bucket_w = (buf_dimensions.w + num_buckets - 1) / num_buckets;

        let kernel = Kernel::builder()
            .program(&program)
            .name(kernel_name)
            .queue(queue_ref.clone())
            .global_work_size(buf_len)
            .arg(&gpu_frame_buf)
            .arg(buf_dimensions.w)
            .arg(buf_dimensions.h)
            .arg(&flat_rects_buf)
            .arg(&offsets_buf)
            .arg(&counts_buf)
            .arg(num_buckets)
            .arg(bucket_w)
            .build()
            .map_err(|e| format!("Failed to build kernel: {e}"))?;

        Ok(KernelBundle {
            kernel,
            buffers: vec![
                gpu_frame_buf,
                flat_rects_buf,
                offsets_buf,
                counts_buf,
            ],
        })
    }
    #[cfg(not(feature = "gpu"))]
    {
        let _ = cpu_frame_buf;
        let _ = buf_dimensions;
        let _ = rects;
        let _ = default_color;
        let _ = num_buckets;
        let _ = gpu_context;
        Err("GPU support is not enabled at compile time.".to_string())
    }
}

pub fn choose_num_buckets<T: Numeric + Copy>(
    rects: &Vec<&RectArea<T>>,
    buf_width: u32,
    min: u32,
    max: u32,
) -> u32 {
    let n = rects.len().max(1) as u32;
    let avg_w = rects.iter().map(|r| r.dimensions.w.to_u32()).sum::<u32>() / n;
    let avg_w = avg_w.max(1);
    let buckets = (buf_width + avg_w - 1) / avg_w;
    buckets.clamp(min, max)
}


/// Helper for N-bucket rect flattening and pointer tables (as above)
fn bucketize_rects<T: Numeric + Copy>(
    rects: &[&RectArea<T>],
    buf_width: u32,
    n_buckets: u32,
    default_color: u32,
) -> (Vec<u32>, Vec<u32>, Vec<u32>) {
    let bucket_w = (buf_width + n_buckets - 1) / n_buckets;
    let mut buckets: Vec<Vec<u32>> = vec![Vec::new(); n_buckets as usize];

    for rect in rects {
        let x = rect.top_left.x.to_u32();
        let w = rect.dimensions.w.to_u32();
        let start_bucket = (x / bucket_w).min(n_buckets - 1);
        let end_bucket = ((x + w - 1) / bucket_w).min(n_buckets - 1);
        for bucket in start_bucket..=end_bucket {
            buckets[bucket as usize].push(x);
            buckets[bucket as usize].push(rect.top_left.y.to_u32());
            buckets[bucket as usize].push(w);
            buckets[bucket as usize].push(rect.dimensions.h.to_u32());
            buckets[bucket as usize].push(rect.color.unwrap_or(default_color));
        }
    }

    // Flatten all buckets into one buffer, and build offset/count tables.
    let mut flat: Vec<u32> = Vec::new();
    let mut offsets = Vec::with_capacity(n_buckets as usize);
    let mut counts = Vec::with_capacity(n_buckets as usize);
    let mut curr = 0;
    for bucket in buckets.iter() {
        // println!("bucket # {}, len: {}, bucket:{:?}", offsets.len(), bucket.len(), bucket);
        offsets.push(curr as u32 / 5);
        counts.push((bucket.len() / 5) as u32);
        flat.extend(bucket);
        curr += bucket.len();
    }

    (flat, offsets, counts)
}
